version: '2'
networks:
  backend:
    external: true

services:
  react-client:
    command: yarn dev
    build:
      context: .
      dockerfile: .docker/Dockerfile.dev
    container_name: react-client
    restart: always
    volumes:
      - "./app:/app"
    ports:
      - "3000:3000"
    networks:
      - backend